version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    command: gunicorn PharmaQ.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8888:8000"
    depends_on:
      - db
    environment:
      - DEBUG=0
      - DB_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - SECRET_KEY=temp-secret-key-lkjlkfjg-sdfgkj-dfkjndf-sdf12dsfb-fgb
      - DEFAULT_FROM_EMAIL=support@pharma-q.org

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"

  nginx:
    image: nginx
    container_name: nginx_server
    ports:
      - "88:80"
    depends_on:
      - django
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/usr/share/nginx/html/staticfiles
      - ./media:/usr/share/nginx/html/media

volumes:
  postgres_data:
