# Generated by Django 5.1.3 on 2024-11-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20241111_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
    ]
