# Generated by Django 5.1.3 on 2024-11-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_is_approved_alter_appuser_is_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='professional_card',
            field=models.ImageField(blank=True, null=True, upload_to='professional_cards/'),
        ),
    ]
