# Generated by Django 5.1.3 on 2024-12-08 09:10

import PharmaQ.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20241206_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='professional_card',
            field=models.ImageField(blank=True, null=True, upload_to='professional_cards/', validators=[PharmaQ.accounts.validators.ImageSizeValidator(5)]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_imgs/', validators=[PharmaQ.accounts.validators.ImageSizeValidator(5)]),
        ),
    ]
